version: '3.8'
services:
  dev-db: 
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nhathuy2409
      POSTGRES_DB: nest-crud
    networks:
      1Huy:
networks:
  1Huy: